DotnetSquad/hris

hris.sln
pull_request_template.md

feat: add pull request template

---

.gitignore
API/appsettings.json
Client/appsettings.json

feat: add obj and bin to .gitignore on each project and appsetting.json

---

API/Models/BaseEntity.cs

feat: create base entity model

---

API/Models/Job.cs

feat: create job model

---

API/API.csproj
API/Contracts/IBaseRepository.cs
API/Models/AccountRole.cs
API/Models/BaseEntity.cs
API/Models/Profile.cs
Client/Client.csproj

update profile, base entity and ibaserepository

---

API/Utilities/Enums/GenderEnum.cs
API/Utilities/Enums/MarriageStatusEnum.cs
API/Utilities/Enums/StatusEnum.cs

feat: create enum

---

.gitignore

feat: add .vscode to .gitignore

---

API/Models/Account.cs

feat: add cardinality account model

---

API/Models/AccountRole.cs

feat: add cardinality account role model

---

API/Models/Employee.cs

feat: add cardinality employee model

---

API/Models/Role.cs

feat: add cardinality role model

---

API/Models/Overtime.cs

feat: add cardinality overtime model

---

API/Models/Profile.cs

feat: add cardinality profile model

---

API/Models/Employee.cs
API/Models/Job.cs

feat: add cardinality jobs model

---

README.md

chore: add authors in README.md

---

API/Models/Department.cs

feat: add cardinality department model

---

API/Models/Department.cs

feat: update department models

---

API/Data/ApplicationDbContext.cs

feat: create db context

---

.gitignore
hris.sln

update sln to add blazorapp to solution

---

API/API.csproj
API/Contracts/IBaseRepository.cs
API/Contracts/IJobRepository.cs

feat: create job interface

---

API/Contracts/IEmployeeRepository.cs

feat: create employee interface

---

API/Contracts/IDepartmentRepository.cs

feat: create deparment interface

---

API/Contracts/IAccountRoleRepository.cs

feat: create account role interface

---

API/API.csproj
API/Contracts/IOvertimeRepository.cs

feat: create overtime interface

---

API/Contracts/IRoleRepository.cs

feat: create role interface

---

API/Contracts/IProfileRepository.cs

feat: create profile interface

---

API/Repositories/BaseRepository.cs

feat: create base repository

---

API/Contracts/IAccountRepository.cs

feat: create account interface

---

API/Repositories/ProfileRepository.cs

feat: create profile repository

---

API/Repositories/RoleRepository.cs

feat: create role repository

---

API/Repositories/JobRepository.cs

feat: create job repository

---

API/Repositories/OvertimeRepository.cs

feat: create overtime repository

---

API/Repositories/AccountRepository.cs

feat: create account repository

---

API/Repositories/AccountRoleRepository.cs

feat: create account role repository

---

API/API.csproj
API/DataTransferObjects/Roles/RoleDtoCreate.cs
API/DataTransferObjects/Roles/RoleDtoGet.cs
API/DataTransferObjects/Roles/RoleDtoUpdate.cs

feat: create role dto

---

API/DataTransferObjects/Departments/DepartmentDtoCreate.cs
API/DataTransferObjects/Departments/DepartmentDtoGet.cs
API/DataTransferObjects/Departments/DepartmentDtoUpdate.cs

feat: create department dto

---

API/DataTransferObjects/Profiles/ProfileDtoCreate.cs
API/DataTransferObjects/Profiles/ProfileDtoGet.cs
API/DataTransferObjects/Profiles/ProfileDtoUpdate.cs

feat: create profile dto

---

API/DataTransferObjects/AccountRoles/AccountRoleDtoCreate.cs
API/DataTransferObjects/AccountRoles/AccountRoleDtoGet.cs
API/DataTransferObjects/AccountRoles/AccountRoleDtoUpdate.cs

feat: create account role dto

---

API/DataTransferObjects/Overtimes/OvertimeDtoCreate.cs
API/DataTransferObjects/Overtimes/OvertimeDtoGet.cs
API/DataTransferObjects/Overtimes/OvertimeDtoUpdate.cs
API/Migrations/20230811130225_UpdateOvertime.Designer.cs
API/Migrations/20230811130225_UpdateOvertime.cs
API/Models/Overtime.cs

feat: create overtime dto and update model

---

API/DataTransferObjects/Accounts/AccountDtoCreate.cs
API/DataTransferObjects/Accounts/AccountDtoGet.cs
API/DataTransferObjects/Accounts/AccountDtoUpdate.cs

feat: create account dto

---

API/Migrations/20230811131129_UpdateOvertime.Designer.cs
API/Migrations/20230811131129_UpdateOvertime.cs
API/Migrations/ApplicationDbContextModelSnapshot.cs
API/Models/Overtime.cs

feat: update migration overtime

---

API/DataTransferObjects/Employees/EmployeeDtoCreate.cs
API/DataTransferObjects/Employees/EmployeeDtoGet.cs
API/DataTransferObjects/Employees/EmployeeDtoUpdate.cs

feat: create employee dto

---

API/DataTransferObjects/Jobs/JobDtoCreate.cs
API/DataTransferObjects/Jobs/JobDtoGet.cs
API/DataTransferObjects/Jobs/JobDtoUpdate.cs

feat: create job dto

---

API/Services/AccountRoleService.cs

feat: create account role service

---

API/Services/AccountRoleService.cs
API/Services/AccountService.cs

feat: create account service

---

API/Services/JobService.cs

feat: create job service

---

API/Services/AccountService.cs
API/Services/RoleService.cs

feat: create role service

---

API/Services/DepartmentService.cs

feat: create department service

---

API/Services/EmployeeService.cs

feat: create employee service

---

API/Services/ProfileService.cs

feat: create profile service

---

API/Utilities/Handlers/ResponseHandler.cs

feat: create response handler

---

API/Controllers/JobController.cs
API/Program.cs

feat: create job controller

---

API/Controllers/OvertimeController.cs
API/Program.cs

feat: create overtime controller

---

API/Controllers/EmployeeController.cs
API/Program.cs

feat: create employee controller

---

API/Controllers/JobController.cs
API/Controllers/RoleController.cs
API/Program.cs

feat: create role controller

---

API/Controllers/AccountRoleController.cs
API/Program.cs
API/Services/AccountRoleService.cs

feat: create accountrole controller

---

API/Controllers/DepartmentController.cs
API/Program.cs

feat: create department controller

---

API/DataTransferObjects/Employees/EmployeeDtoCreate.cs
API/DataTransferObjects/Employees/EmployeeDtoGet.cs
API/DataTransferObjects/Employees/EmployeeDtoUpdate.cs
API/Migrations/20230815064438_update-employee-model.Designer.cs
API/Migrations/20230815064438_update-employee-model.cs
API/Models/Employee.cs

feat: update employee model

---

API/Controllers/AccountController.cs
API/Controllers/AccountRoleController.cs
API/Controllers/DepartmentController.cs
API/Controllers/EmployeeController.cs
API/Controllers/JobController.cs
API/Controllers/OvertimeController.cs
API/Controllers/ProfileController.cs
API/Controllers/RoleController.cs
API/Services/AccountRoleService.cs
API/Services/AccountService.cs
API/Services/DepartmentService.cs
API/Services/EmployeeService.cs
API/Services/JobService.cs
API/Services/OvertimeService.cs
API/Services/ProfileService.cs
API/Services/RoleService.cs

refactor: variable name, routing controller and some services

---

API/Contracts/IEmailHandler.cs
API/Program.cs
API/Utilities/Handlers/EmailHandler.cs

feat: create email handler

---

API/API.csproj
API/Contracts/ITokenHandler.cs
API/Program.cs
API/Utilities/Handlers/TokenHandler.cs
BlazorApp/BlazorApp.csproj

feat: create token handler
